name: FileConverterWorkflow

env:
  SOLUTION_DIR: "TestProject1/Solution/FileFormatConverter.sln"
  DOTNET_VERSION: 3.1
  
on:
  pull_request:
    branches: [ master ]
    paths:
    - 'TestProject1/**'
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest]
            # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore TestProject1/Solution/FileFormatConverter.sln
    - name: Build
      run: dotnet build --no-restore TestProject1/Solution/FileFormatConverter.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal $SOLUTION_DIR
    - name: Publish CLI
      run: dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true TestProject1/Solution/FileFormatConverter.sln
